### PR TITLE
Add license headers and do some basic code clean up.

### PR DESCRIPTION
**Pull request by scottpurdy**
@baroobob and @breznak - Can you both approve this PR? I'd like to make sure that the copyright headers are in all of the code files. I hope to do some more work on vision examples and want to make sure this code is explicitly under Numenta copyright before working in this repo.

### CODE REVIEW

**Comment by breznak** [comment]
@scottpurdy I'm :+1: with the PR, although most code comes from @baroobob . 
Just a question, it's fine if you work on the repo and require your contributions to be licensed to Numenta, but if (not that it happened yet) any contributors wanted to be GPL only, it should still be acceptable, right?

**Comment by scottpurdy** [comment]
@breznak We can't accept contributions from people that don't sign the Numenta CLA because it may limit what Numenta can do with the code.

**Comment by breznak** [comment]
I know, but that's the difference between numenta and nupic-community
repos, isn't it? (like NupicStudio is in community and has nothing to do
with Numenta CLA)

**Comment by scottpurdy** [comment]
@breznak - yes, exactly! And so this PR is to allow me to move the repo from community to `numenta/`. I wouldn't do this for something like NuPIC Studio but vision is pretty core and especially with some vision code from NuPIC being moved over to here we need to either bring this repo under Numenta copyright or start a new repo for Numenta work that we do own full copyright for. I believe that @baroobob 's intent was for this to be moved over and I would prefer to have his work included hence this PR :)

**Comment by breznak** [comment]
I see, I didn't get your point of moving this under `numenta/`. 
And yay :+1: :+1: if you'll join me on some vision related endeavors with nupic! :wink:

**Comment by baroobob** [comment]
Sounds good to me.  :thumbsup:

I've been busy the last few months moving to Houston and starting a new job, but very happy to hear this code is getting used.

**Comment by scottpurdy** [comment]
Congrats on the job!

**Pull request merged**
